/** Shared by both sides, CPU decisions and charge feedback. Timings are in seconds. */
export const COMBAT = {
  attackBuffer: 0.16,
  comboWindow: 0.85,
  jabRecovery: 0.22,
  finisherRecovery: 0.52,
  specialCharge: 1.3,
  ultimateCharge: 2,
  ultimateWindup: 0.5,
  recoveryRise: 900,
  recoveryChargeRise: 150,
  recoveryDrift: 210,
  ultimateCost: 60,
  normalStun: 0.5,
  stunEscape: 0.22,
  meterOnHit: 0.5,
  meterOnDamage: 0.2,
  meterOnParry: 10,
  meterOnHazardParry: 6,
  meterOnGuard: 1,
  meterPickup: 20,
  bossStocks: 1,
  bossDamageTaken: 0.55,
  bossKnockbackTaken: 0.55,
  bossDamageMultiplier: 1.25,
  bossAwakenDamage: 50,
  bossMeterPerSecond: 2.5,
  awakenedMeterPerSecond: 5,
  awakenedSpeed: 1.2,
  awakenedRegeneration: 2.25,
} as const;
